#!/usr/bin/env bash

set -exo pipefail

main() {
  run_ansible_playbook -vv site.yml --ask-become-pass
}

run_ansible_playbook() {
  python3 -m pip install --user pipenv
  python3 -m pipenv install --dev
  python3 -m pipenv run ansible-playbook "$@"
}

main
