#!/usr/bin/env bash

set -exo pipefail

install_virtualenv() {
  pip || sudo easy_install pip
  sudo pip install virtualenv
}

virtualenv || install_virtualenv
virtualenv venv
source venv/bin/activate
which ansible-playbook || pip install ansible
ansible-playbook -vv site.yml --ask-become-pass
