#!/usr/bin/env bash

set -exo pipefail

use_venv() {
  source venv/bin/activate
  which ansible-playbook || pip install ansible
}

create_venv() {
  virtualenv venv
  use_venv
}

use_venv || create_venv
ansible-playbook -vv site.yml --ask-sudo-pass
