- hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: "/usr/bin/env python"
    homebrew_taps:
      - caskroom/cask
      - caskroom/versions
  roles:
    - geerlingguy.homebrew
    - common
    - dotfiles
    - atom
