- name: Install whatever implementation
  pacman:
    name:
      - cronie
    state: present
  become: yes

- name: Enable and/or start
  service:
    name: cronie
    enabled: yes
    state: started
  become: yes
