- name: GPG public keys
  apt_key:
    url: '{{ item }}'
    state: present
  with_items:
    - 'https://download.docker.com/linux/ubuntu/gpg'
    - 'https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg'
  become: yes

- name: APT repositories
  apt_repository:
    repo: '{{ item }}'
    state: present
  with_items:
    - 'ppa:no1wantdthisname/ppa'
    - 'ppa:rvm/smplayer'
    - 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'
    - 'deb https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/repos/debs/ vscodium main'
  become: yes

- name: Common packages
  apt:
    name:
      - chromium-browser
      - deluge-gtk
      - smplayer
      - git
      - p7zip
      - gitg
      - lm-sensors
      - mpv
      - terminator
      - docker-ce
      - docker-compose
      - unp
      # FIXME: missing tzdata package
      # - openjdk-7-source
      # - openjdk-7-jdk
      - openjdk-8-source
      - openjdk-8-jdk
      - codium
    state: present
  become: yes

- name: Install nodejs
  include_role:
    name: geerlingguy.nodejs
  vars:
    ansible_become: yes
