# Idea from gantsign/ansible-role-atom
- name: Install Atom packages
  shell: >
    apm list --bare | grep -E '^{{ item }}@'
    && echo 'Already installed.'
    || apm install '{{ item }}'
  with_items: "{{ atom_packages }}"
  register: apm_result
  changed_when: "'Already installed.' not in apm_result.stdout"
