- name: APT repositories
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "ppa:fish-shell/release-3"
  become: yes

- name: install
  apt:
    name:
      - fish
    state: present
  become: yes
