- name: PPA repositories
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "ppa:no1wantdthisname/ppa"
    - "ppa:rvm/smplayer"
    - "deb https://apt.dockerproject.org/repo ubuntu-{{ ansible_distribution_release }} main"
  become: yes

- name: Common packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - fish
    - chromium-browser
    - smplayer
    - git
    - mpv
    - docker-engine
  become: yes
