- name: PPA repositories
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "ppa:no1wantdthisname/ppa"
    - "ppa:rvm/smplayer"
    - "ppa:webupd8team/atom"
    - "deb https://apt.dockerproject.org/repo ubuntu-{{ ansible_distribution_release }} main"
  when: ansible_pkg_mgr == 'apt'
  become: yes

- name: Common packages
  apt:
    name:
      - atom
      - fish
      - chromium-browser
      - deluge-gtk
      - smplayer
      - git
      - p7zip
      - gitg
      - mpv
      - docker-engine
      - docker-compose
      - unp
      # FIXME: missing tzdata package
      # - openjdk-7-source
      # - openjdk-7-jdk
      - openjdk-8-source
      - openjdk-8-jdk
    state: present
  when: ansible_pkg_mgr == 'apt'
  become: yes

- name: Common packages (Mac)
  homebrew:
    name:
      - fish
      - httpie
      - jq
      - nano
      - node
      - terraform
      - the_silver_searcher
      - unp
      - yarn
      - youtube-dl
      - libav
    state: present
  when: ansible_os_family == 'Darwin'

- name: Common packages (Mac)
  homebrew_cask:
    name:
      - adoptopenjdk8
      - android-file-transfer
      - docker
      - firefox
      - font-anonymouspro-nerd-font-mono
      - font-aurulentsansmono-nerd-font-mono
      - font-dejavusansmono-nerd-font-mono
      - font-droidsansmono-nerd-font-mono
      - font-fira-mono
      - font-hack-nerd-font-mono
      - font-inconsolata-nerd-font-mono
      - font-input
      - font-merriweather
      - font-merriweather-sans
      - font-monoid-nerd-font-mono
      - font-mononoki-nerd-font-mono
      - font-robotomono-nerd-font-mono
      - font-sourcecodepro-nerd-font-mono
      - fork
      - gimp
      - google-chrome
      - intellij-idea-ce
      - microsoft-teams
      - postman
      - skype-for-business
      - slack
      - visual-studio-code-insiders
      - vlc
      - vox
      - vox-preferences-pane
      - vscodium
    state: present
  when: ansible_os_family == 'Darwin'

