- name: PPA repositories
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "ppa:no1wantdthisname/ppa"
    - "ppa:rvm/smplayer"
    - "ppa:webupd8team/atom"
    - "deb https://apt.dockerproject.org/repo ubuntu-{{ ansible_distribution_release }} main"
  when: ansible_pkg_mgr == 'apt'
  become: yes

- name: Common packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - atom
    - fish
    - chromium-browser
    - deluge-gtk
    - smplayer
    - git
    - p7zip
    - gitg
    - mpv
    - docker-engine
    - docker-compose
    - unp
    # FIXME: missing tzdata package
    # - openjdk-7-source
    # - openjdk-7-jdk
    - openjdk-8-source
    - openjdk-8-jdk
  when: ansible_pkg_mgr == 'apt'
  become: yes

- name: Common packages (Mac)
  homebrew:
    name: "{{ item }}"
    state: present
  when: ansible_os_family == 'Darwin'
  with_items:
    - fish
    - unp
    - youtube-dl

- name: Common packages (Mac)
  homebrew_cask:
    name: "{{ item }}"
    state: present
  when: ansible_os_family == 'Darwin'
  with_items:
    - android-file-transfer
    - atom
    - docker
    - firefox
    - google-chrome
    - java
    - slack
    - vlc
