- hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: '/usr/bin/env python3'
  roles:
    - dotfiles
    - fonts
    - cron
    - fish-shell
    - eclipse
    - common
    - pulumi
    - role: 'hacks-eluktronics-thinn15'
      when: ansible_system_vendor == 'Eluktronics' and ansible_product_name == 'THINN-15'
